version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PIP_NO_CACHE_DIR=off
      - PIP_DISABLE_PIP_VERSION_CHECK=on
      - POETRY_HOME=/opt/poetry
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - POETRY_NO_INTERACTION=1
    volumes:
      - .:/workspace
    working_dir: /workspace
